# Generated by Django 4.1 on 2024-11-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_message_sender_chatonetoone_alter_message_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.room'),
        ),
        migrations.DeleteModel(
            name='ChatOneToOne',
        ),
    ]
