# Generated by Django 4.1 on 2024-11-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_userimage_delete_userabstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_VNPAY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('order_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
