version: '3.7'
services:
  db:
    container_name: "mysql"
    image: mysql:5.7
    environment:
      DATABASE_NAME: 'mydb'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'root'
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "13306:3306"
    # expose:
    #   - "3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    networks:
      - my-network

  django_app:
    image: django_app
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "django_app"
    depends_on:
      - db
    # expose:
    #   - 8000
    ports:
      - "8000:8000"
    
    tty: true
    stdin_open: true
    command: >
      bash -c "(python manage.py migrate) && (python manage.py runserver 0.0.0.0:8000)"
    volumes:
      - /home/dang-den/Desktop/myproject/static:/code/static
      - /home/dang-den/Desktop/myproject/media:/code/media
      - /home/dang-den/Desktop/myproject/:/code/    #mount code
    env_file:
      - "Django/.env"
    restart: always
    networks:
      - my-network

  nginx-server:
    build: ./nginx
    container_name: "nginx_app"
    image: nginx
    depends_on:
      - django_app
    volumes:
      - /home/dang-den/Desktop/nginx/log:/var/log/nginx
      # - /home/dang-den/Desktop/project/collected_static:/var/www/html/static/
      # - /home/dang-den/Desktop/project/media/:/var/www/html/media/
      - /home/dang-den/Desktop/myproject/static:/var/www/html/static
      - /home/dang-den/Desktop/myproject/media:/var/www/html/media
      # - /home/dang-den/Desktop/myproject/nginx:/etc/nginx/conf.d/default.conf/
    ports:
      # - "443:443"
      - "80:80"
    restart: always
    networks:
      - my-network
    

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
